[slc] add a copy of the `ot_crash_handler` component that uses the vendor extension to print crash info instead of using the `internal_app_init` event
This also adds a ot-efr32 copy of `diagnostic.c` which fixes an `include` error.
```bash
/Users/matran/repos/ot-efr32/src/legacy_hal/diagnostic.c:31:10: fatal error: logging.h: No such file or directory
   31 | #include <logging.h>
      |          ^~~~~~~~~~~
```